version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - echo 'Run tests'
      - sls deploy
  post_build:
    commands:
      - sls deploy
